version: "2"
run:
  modules-download-mode: readonly
  issues-exit-code: 1
linters:
  default: none
  enable:
    - errcheck
    - errorlint
    - govet
    - ineffassign
    - misspell
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unused
  settings:
    staticcheck:
      checks:
        - -SA1019
        - all
  exclusions:
    generated: lax
    presets:
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofumpt
    - goimports
  settings:
    gofumpt:
      extra-rules: true
    goimports:
      local-prefixes:
        - github.com/andrewkroh/go-ingest-node
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
